name: Rust CI Auto-Merge

on:
  push:
    branches: [ "unstable" ]

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: cargo fmt --all -- --check

  optimization-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2

      - run: cargo clippy --all-targets --all-features -- -D warnings

  functionality-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2

      - run: cargo test --all-targets --all-features

  deploy-to-master:
    needs: [formatting-check, optimization-check, functionality-test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin master:master
          commit_logs=$(git log master..origin/unstable --oneline | sed 's/^/* /')
          pr_body=$(cat <<EOF
          Automatically generated by GitHub Actions:

          $commit_logs
          EOF
          )

          pr_url=$(gh pr create \
            --base master \
            --head unstable \
            --title "Auto-Merge: unstable -> master" \
            --body "$pr_body")
          gh pr merge "$pr_url" --merge --delete-branch=false
