name: Test & Publish

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  validate:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Format Check
        run: cargo fmt --all -- --check

      - name: Optimization Check
        run: cargo clippy --locked --all-targets --all-features -- -D warnings

      - name: Functionality Test
        run: cargo test --all-targets --all-features --locked

  publish:
    name: Publish
    needs: validate
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          LOCAL_VERSION=$(cargo pkgid | cut -d# -f2 | cut -d: -f2)
          CRATE_NAME=$(cargo pkgid | cut -d# -f1 | awk -F/ '{print $NF}' | cut -d: -f1)

          if cargo search $CRATE_NAME | grep -q "$CRATE_NAME = \"$LOCAL_VERSION\""; then
            echo "Version $LOCAL_VERSION is already exists. Abort."
            exit 0
          fi
          
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")

          echo "## [v$LOCAL_VERSION] - $(date +'%Y-%m-%d')" > temp_changelog.md
          echo "" >> temp_changelog.md

          if git log $LAST_TAG..HEAD --format="%s" | grep -q -E "^[a-z]+(\([a-z]+\))?!:"; then
            echo "### ⚠️ Breaking Changes" >> temp_changelog.md
            git log $LAST_TAG..HEAD --format="- %s" | grep -E "^- [a-z]+(\([a-z]+\))?!:" >> temp_changelog.md
            echo "" >> temp_changelog.md
          fi
          if git log $LAST_TAG..HEAD --format="%s" | grep -q -E "^feat(\([a-z0-9_-]+\))?:"; then
            echo "### Features" >> temp_changelog.md
            git log $LAST_TAG..HEAD --format="- %s" | grep -E "^- feat(\([a-z0-9_-]+\))?:" >> temp_changelog.md
            echo "" >> temp_changelog.md
          fi
          if git log $LAST_TAG..HEAD --format="%s" | grep -q -E "^refactor(\([a-z0-9_-]+\))?:"; then
            echo "### Code Refactoring" >> temp_changelog.md
            git log $LAST_TAG..HEAD --format="- %s" | grep -E "^- refactor(\([a-z0-9_-]+\))?:" >> temp_changelog.md
            echo "" >> temp_changelog.md
          fi
          if git log $LAST_TAG..HEAD --format="%s" | grep -q -E "^perf(\([a-z0-9_-]+\))?:"; then
            echo "### Performance Improvements" >> temp_changelog.md
            git log $LAST_TAG..HEAD --format="- %s" | grep -E "^- perf(\([a-z0-9_-]+\))?:" >> temp_changelog.md
            echo "" >> temp_changelog.md
          fi
          if git log $LAST_TAG..HEAD --format="%s" | grep -q -E "^fix(\([a-z0-9_-]+\))?:"; then
            echo "### Bug Fixes" >> temp_changelog.md
            git log $LAST_TAG..HEAD --format="- %s" | grep -E "^- fix(\([a-z0-9_-]+\))?:" >> temp_changelog.md
            echo "" >> temp_changelog.md
          fi

          if [ -f CHANGELOG.md ]; then
            cat CHANGELOG.md >> temp_changelog.md
          fi
          mv temp_changelog.md CHANGELOG.md

          git add CHANGELOG.md
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update changelog for v$LOCAL_VERSION [skip ci]"

          git tag "v$LOCAL_VERSION"
          git pull --rebase origin main || { echo "Rebase failed"; exit 1; }
          git push origin main
          git push origin "v$LOCAL_VERSION"

          cargo publish --token $CARGO_REGISTRY_TOKEN
